name: Slack Notification

on:
  repository_dispatch:
    types: [send-slack-message]

jobs:
  slack-notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Send Notification to Slack
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: |
        MESSAGE="${{ github.event.client_payload.message }}"
        curl -X POST -H 'Content-type: application/json' --data "{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"${MESSAGE}\"}}]}" $WEBHOOK_URL
