name: Send dynamic message to Slack

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to send to Slack'
        required: true
        default: 'Emergency alarm triggered!'

jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        run: |
          MESSAGE="${{ github.event.inputs.message }}"
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${MESSAGE}\"}" ${{ secrets.WEBHOOK_URL }}
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
